def initialize():
    global IP_ADDRESS_CONTAINERS
    global PORT_CONTAINERS_START
    global FLAG_LANGUAGE
    global FLAG_PREFIX
    
    IP_ADDRESS_CONTAINERS = "172.17.0.1"
    PORT_CONTAINERS_START = 80
    FLAG_LANGUAGE = "english"
    FLAG_PREFIX = "CTF2024"